 hosts: servidores
  become: true
  tasks:
    - name: "Crear usuario"
        user:
            name: lpruna
            password: $y$j9T$VXxYB3E62Xy6H0izfHqzu0$ZIPgKuV4nft0wDdYGiuGM5HB6z9wvqkTroGVe9ktFL5
            home: /home/lpruna
            groups: sudo
            shell: /bin/bash
    - name: "Descargar fichero de una url"
        get_url:
            dest: https://wordpress.org/latest.zip
