- hosts: servidores
  become: true
  tasks:
    - name: "Crear usuario"
      user:
        name: larap
        password: $y$j9T$VXxYB3E62Xy6H0izfHqzu0$ZIPgKuV4nft0wDdYGiuGM5HB6z9wvqkTroGVe9ktFL5
        home: /home/larap
        groups: sudo
        shell: /bin/bash
    - name: "Descargar fichero de una url"
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /home/larap
    - name: "Instalar el paquete mariadb"
      apt:
        name:
          - git
          - unzip
          - mariadb-server
          - python3-mysqldb
    - name: "Descomprimir fichero"
      unarchive:
        remote_src: yes
        src: /home/larap/wordpress-5.8.1.zip
        dest: /home/larap
    - name: "Crear una base de datos en mariadb"
      mysql_db:
        name: larap_wordpress
        state: present
    - name: "Crear usuario en la base de datos"
      mysql_user:
        name: larap
        password: $y$j9T$3MMrs9Ot9YJWGK35VJiJS/$6cIR6UmpWl8WTunYLtjaYldKLKylMpRuOrMx5YH.VO2
        priv: larap_wordpress.*:ALL,GRANT
    - name: "Clonar un repositorio en el home del usuario creado"
      git:
        clone: no
        repo: https://github.com/josedom24/ansible_ejemplos.git
        dest: /home/larap
